platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.4.2

inputs:
- name: repo

run:
  # path: repo/ci/build.sh
  path: bash
  args:
  - -exc
  - |
  
    pushd repo
      bundle install
      bundle exec rspec
    popd