resources:
- name: flight-school-repo
  type: git
  source:
    uri: https://github.com/rockotseng/flight-school
    branch: master

- name: flight-school-development
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))

jobs:
- name: build
  plan:
  - get: flight-school-repo
    trigger: true
  - task: build
    file: flight-school-repo/ci/build.yml
    input_mapping:
      repo: flight-school-repo
  - put: flight-school-development
    params:
      manifest: flight-school-repo/manifest.yml
      environment_variables:
        SPRING_PROFILES_ACTIVE: development