resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/rockotseng/flight-school
    branch: master

- name: flight-school-development
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: rockos-flight-school
    space: development

jobs:
- name: development
  plan:
  - get: flight-school
    trigger: true
  - task: build
    file: flight-school/ci/build.yml
  - put: flight-school-development
    params:
      manifest: flight-school/manifest.yml
      environment_variables:
        SPRING_PROFILES_ACTIVE: development